version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - myapp-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - myapp-network
  yarn:
    image: node:14
    volumes:
      - .:/app
    working_dir: /app
networks:
  myapp-network: